export default function getCourses() {
    return new Promise((res, rej) => {
        setTimeout(() => {
            const shouldFail = false;

            if (shouldFail) {
                rej({ message: "Failed to fetch courses" });
                return;
            }

            res([
                    {
                        id: 1,
                        title: "React Fundamentals",
                        description: "Learn the basics of React, components and hooks.",
                        level: "Beginner",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 2,
                        title: "Advanced JavaScript",
                        description: "Deep dive into closures, async/await, and patterns.",
                        level: "Advanced",
                        duration: "8h",
                        theme: "Tech",
                    },
                    {
                        id: 3,
                        title: "Web Design Basics",
                        description: "HTML, CSS, and responsive design fundamentals.",
                        level: "Beginner",
                        duration: "5h",
                        theme: "Design",
                    },
                    {
                        id: 4,
                        title: "Node.js Essentials",
                        description: "Build backend services with Express and Node.js.",
                        level: "Beginner",
                        duration: "7h",
                        theme: "Tech",
                    },
                    {
                        id: 5,
                        title: "TypeScript in Practice",
                        description: "Strong typing, interfaces, and real-world TS projects.",
                        level: "Intermediate",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 6,
                        title: "Python for Data Analysis",
                        description: "Analyze datasets using Pandas and NumPy.",
                        level: "Beginner",
                        duration: "9h",
                        theme: "Data",
                    },
                    {
                        id: 7,
                        title: "UI/UX Design Principles",
                        description: "Design usable and beautiful digital experiences.",
                        level: "Beginner",
                        duration: "4h",
                        theme: "Design",
                    },
                    {
                        id: 8,
                        title: "Docker & Containers",
                        description: "Package and deploy apps using Docker.",
                        level: "Intermediate",
                        duration: "5h",
                        theme: "Tech",
                    },
                    {
                        id: 9,
                        title: "REST APIs with Express",
                        description: "Create scalable RESTful APIs from scratch.",
                        level: "Intermediate",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 10,
                        title: "AWS Cloud Foundations",
                        description: "Understand core AWS services and architecture.",
                        level: "Beginner",
                        duration: "7h",
                        theme: "Tech",
                    },
                    {
                        id: 11,
                        title: "Next.js for Production",
                        description: "Build fast React apps with SSR and routing.",
                        level: "Advanced",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 12,
                        title: "SQL for Developers",
                        description: "Master queries, joins, and indexes.",
                        level: "Beginner",
                        duration: "5h",
                        theme: "Data",
                    },
                    {
                        id: 13,
                        title: "GraphQL Essentials",
                        description: "Flexible APIs with Apollo and GraphQL.",
                        level: "Intermediate",
                        duration: "4h",
                        theme: "Tech",
                    },
                    {
                        id: 14,
                        title: "Cybersecurity Basics",
                        description: "Protect systems and networks from attacks.",
                        level: "Beginner",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 15,
                        title: "Machine Learning Intro",
                        description: "Supervised models and evaluation techniques.",
                        level: "Intermediate",
                        duration: "8h",
                        theme: "Data",
                    },
                    {
                        id: 16,
                        title: "Kubernetes Fundamentals",
                        description: "Container orchestration and scaling.",
                        level: "Advanced",
                        duration: "7h",
                        theme: "Tech",
                    },
                    {
                        id: 17,
                        title: "Mobile Apps with React Native",
                        description: "Build cross-platform apps for iOS and Android.",
                        level: "Intermediate",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 18,
                        title: "DevOps Foundations",
                        description: "CI/CD pipelines and automation workflows.",
                        level: "Beginner",
                        duration: "5h",
                        theme: "Tech",
                    },
                    {
                        id: 19,
                        title: "Figma for Designers",
                        description: "Prototyping and collaboration for UI teams.",
                        level: "Beginner",
                        duration: "3h",
                        theme: "Design",
                    },
                    {
                        id: 20,
                        title: "Clean Code Practices",
                        description: "Write maintainable and readable software.",
                        level: "Intermediate",
                        duration: "4h",
                        theme: "Tech",
                    },
                    {
                        id: 21,
                        title: "Blockchain Fundamentals",
                        description: "Distributed ledgers and smart contracts.",
                        level: "Beginner",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 22,
                        title: "C# for Web Development",
                        description: "Build web apps using ASP.NET Core.",
                        level: "Intermediate",
                        duration: "7h",
                        theme: "Tech",
                    },
                    {
                        id: 23,
                        title: "iOS Development with Swift",
                        description: "Create native apps for Apple devices.",
                        level: "Advanced",
                        duration: "9h",
                        theme: "Tech",
                    },
                    {
                        id: 24,
                        title: "Android with Kotlin",
                        description: "Modern Android app development techniques.",
                        level: "Intermediate",
                        duration: "8h",
                        theme: "Tech",
                    },
                    {
                        id: 25,
                        title: "Power BI Analytics",
                        description: "Build dashboards and business insights.",
                        level: "Beginner",
                        duration: "5h",
                        theme: "Business",
                    },
                    {
                        id: 26,
                        title: "Excel for Professionals",
                        description: "Advanced formulas, pivot tables and automation.",
                        level: "Beginner",
                        duration: "4h",
                        theme: "Business",
                    },
                    {
                        id: 27,
                        title: "NoSQL with MongoDB",
                        description: "Document databases and schema design.",
                        level: "Intermediate",
                        duration: "6h",
                        theme: "Data",
                    },
                    {
                        id: 28,
                        title: "Linux Command Line",
                        description: "Shell scripting and system navigation.",
                        level: "Beginner",
                        duration: "3h",
                        theme: "Tech",
                    },
                    {
                        id: 29,
                        title: "Ethical Hacking Intro",
                        description: "Pen testing concepts and methodologies.",
                        level: "Advanced",
                        duration: "7h",
                        theme: "Tech",
                    },
                    {
                        id: 30,
                        title: "Data Visualization with D3",
                        description: "Create interactive charts for the web.",
                        level: "Advanced",
                        duration: "6h",
                        theme: "Data",
                    },
                    {
                        id: 31,
                        title: "Project Management Agile",
                        description: "Scrum, Kanban and delivery strategies.",
                        level: "Beginner",
                        duration: "4h",
                        theme: "Business",
                    },
                    {
                        id: 32,
                        title: "Product Design Sprint",
                        description: "Validate ideas quickly using workshops.",
                        level: "Intermediate",
                        duration: "5h",
                        theme: "Product",
                    },
                    {
                        id: 33,
                        title: "SEO Fundamentals",
                        description: "Optimize websites for search engines.",
                        level: "Beginner",
                        duration: "3h",
                        theme: "Marketing",
                    },
                    {
                        id: 34,
                        title: "Marketing Analytics",
                        description: "Track campaigns and ROI with data.",
                        level: "Intermediate",
                        duration: "4h",
                        theme: "Marketing",
                    },
                    {
                        id: 35,
                        title: "Game Development Basics",
                        description: "Core loops and engines for indie games.",
                        level: "Beginner",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 36,
                        title: "Unity for Developers",
                        description: "3D game creation with Unity engine.",
                        level: "Advanced",
                        duration: "9h",
                        theme: "Tech",
                    },
                    {
                        id: 37,
                        title: "AI Prompt Engineering",
                        description: "Craft better prompts for large language models.",
                        level: "Beginner",
                        duration: "2h",
                        theme: "Tech",
                    },
                    {
                        id: 38,
                        title: "Natural Language Processing",
                        description: "Text analysis and transformers basics.",
                        level: "Advanced",
                        duration: "8h",
                        theme: "Data",
                    },
                    {
                        id: 39,
                        title: "Big Data with Spark",
                        description: "Distributed processing and analytics.",
                        level: "Advanced",
                        duration: "7h",
                        theme: "Data",
                    },
                    {
                        id: 40,
                        title: "Web Accessibility",
                        description: "Build inclusive apps following WCAG.",
                        level: "Beginner",
                        duration: "3h",
                        theme: "Design",
                    },
                    {
                        id: 41,
                        title: "Go for Backend Services",
                        description: "Fast APIs using Go and microservices.",
                        level: "Intermediate",
                        duration: "6h",
                        theme: "Tech",
                    },
                    {
                        id: 42,
                        title: "Rust Fundamentals",
                        description: "Memory-safe systems programming.",
                        level: "Advanced",
                        duration: "7h",
                        theme: "Tech",
                    },
                    {
                        id: 43,
                        title: "Digital Marketing Foundations",
                        description: "Learn core concepts of online advertising, funnels and growth.",
                        level: "Beginner",
                        duration: "4h",
                        theme: "Marketing",
                    },
                    {
                        id: 44,
                        title: "Content Strategy & Branding",
                        description: "Create content plans and brand voice for social platforms.",
                        level: "Intermediate",
                        duration: "5h",
                        theme: "Marketing",
                    },
                    {
                        id: 45,
                        title: "Paid Ads Mastery",
                        description: "Run high-converting campaigns on Google and Meta platforms.",
                        level: "Advanced",
                        duration: "6h",
                        theme: "Marketing",
                    },
                    {
                        id: 46,
                        title: "Email Marketing Automation",
                        description: "Build sequences and funnels with automation tools.",
                        level: "Intermediate",
                        duration: "4h",
                        theme: "Marketing",
                    },
                    {
                        id: 47,
                        title: "Social Media Growth Playbook",
                        description: "Grow audiences and engagement organically.",
                        level: "Beginner",
                        duration: "3h",
                        theme: "Marketing",
                    },
                    {
                        id: 48,
                        title: "Startup Fundamentals",
                        description: "Validate ideas, build MVPs and launch products.",
                        level: "Beginner",
                        duration: "5h",
                        theme: "Business",
                    },
                    {
                        id: 49,
                        title: "Business Strategy Essentials",
                        description: "Competitive analysis and market positioning.",
                        level: "Intermediate",
                        duration: "6h",
                        theme: "Business",
                    },
                    {
                        id: 50,
                        title: "Finance for Entrepreneurs",
                        description: "Cash flow, pricing models and budgeting basics.",
                        level: "Intermediate",
                        duration: "5h",
                        theme: "Business",
                    },
                    {
                        id: 51,
                        title: "Leadership & Team Management",
                        description: "Build strong teams and effective communication.",
                        level: "Beginner",
                        duration: "4h",
                        theme: "Business",
                    },
                    {
                        id: 52,
                        title: "Operations & Scaling",
                        description: "Systems, processes and growth frameworks.",
                        level: "Advanced",
                        duration: "6h",
                        theme: "Business",
                    },
                ]);

        }, 1000);
    });
}